apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: email
  namespace: default
scopes:
  - notifications-api
spec:
  type: bindings.smtp
  version: v1
  metadata:
    - name: host
      value: "localhost"
    - name: port
      value: "1025"
    - name: user
      value: "admin"
    - name: password
      value: "password123"
    - name: skipTLSVerify
      value: "true"
    - name: emailFrom
      value: "no-reply@elkhorn.ca"