name: Deploy API - Weather

on:
#   push:
#     branches: [ master ]
#     paths: [ 'src/api.weather/**' ]
#   pull_request:
#     branches: [ master ]
#     paths: [ 'src/api.weather/**' ]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment
        options: [ 'development', 'production']
        default: 'development'
      tag:
        type: string
        required: true
        description: 'Tag to deploy'
        default: 'latest'

permissions:
  id-token: write # needed for Azure CLI login
  contents: read
  packages: write

env:
  PROJECT: 'api-weather' # name of azure web app
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     environment: [development]

    environment: ${{ inputs.environment }}

    env:
      ENV_SHORT: ${{ inputs.environment ==  'development' && 'dev' || 'prod' }}
      IMAGE_NAME: ghcr.io/stormvale/$env.PROJECT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Azure login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy private GHCR image to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.PROJECT }}-elkhorn-${{ env.ENV_SHORT }}-wus2 # api-weather-elkhorn-dev-wus2
          resourceGroup: rg-elkhorn-${{ env.ENV_SHORT }}-wus2
          imageToDeploy: ghcr.io/stormvale/'${{ env.IMAGE_NAME }}:${{ inputs.tag }}'
          #registryUrl: ghcr.io
          # registryUsername: ${{ secrets.GHCR_USERNAME }}
          # registryPassword: ${{ secrets.GHCR_TOKEN }}
